[tool.poetry]
name = "task_tracker"
version = "0.1.0"
description = ""
authors = ["Svyat <life567@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "3.2.*"
Authlib = "0.15.*"
requests = "^2.27.1"
pika = "^1.2.1"
