# Generated by Django 3.2.13 on 2022-05-05 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('username', models.CharField(blank=True, editable=False, max_length=150)),
                ('full_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('email', models.EmailField(blank=True, editable=False, max_length=255)),
                ('role', models.CharField(blank=True, editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to='task_tracker.externaluser')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_reported', to='task_tracker.externaluser')),
            ],
        ),
    ]
