# Generated by Django 3.2.13 on 2022-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='jira_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
