# Generated by Django 3.2.13 on 2022-05-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudiLog',
            new_name='AuditLog',
        ),
    ]
